8.12. Домашнее задание - Массивы
MackenProof/homework pull request #5
Opened 2024-10-13 13:52 UTC by MackenProof

2024-11-02 09:39 UTC, GitEsense requested changes

2024-11-02 09:39 UTC, GitEsense commented on 8-crypto/app.js
> +checkPass('Pavel');
У нас будет всего две функции:
1. crypto - преобразует строку в "шифр", при повторном вызове (для шифрованной строки) - возвращает оригинальный пароль (т.е. обратимость)
2. check - получает в качестве аргументов оригинальный пароль и зашифрованный пароль, возвращает результат сравнения оригинального пароля и обратимости шифрования
Вот пример функции check:
```js
function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypto(encryptedPassword);
}
```

В Вашем случае "обратимость" не выполняется, т.е. для записи вида:
```js
const p = 'password'
const e = crypto(p); // шифрованный пароль (например wosspard - зависит от вашей логики шифрования)
const d = crypto(e); // password

console.log(p,e,d, p === d); // password, wosspard, password, true
```
Результат должен быть как в указанном примере (т.е. оригинальный пароль, шифрованный, расшифрованный и сравнение оригинала и расшифрованного вернёт TRUE)

2024-11-04 13:22 UTC, MackenProof commented on 8-crypto/app.js
> +checkPass('Pavel');
Переписал функции

2024-11-05 08:51 UTC, GitEsense approved these changes

2024-11-05 08:51 UTC, GitEsense commented on 8-crypto/app.js
> +console.log(password, '-',encryptedPassword, '-', decryptedPassword, '-',checkPassword(password));
Всё отлично)
Могу на посмотреть предложить и такой вариант "генератор паролей"
```js
function crypt(password) {
    if (!password || !password.length) {
        return NaN;
    }
    const splitedArray = password.split('');
    if (splitedArray.length < 8) {
        return false;
    }

    const middleIndex = Math.floor(splitedArray.length / 2);
    const firstHalf = splitedArray.slice(0, middleIndex).reverse();
    const secondHalf = splitedArray.slice(middleIndex).reverse();
    const length = secondHalf.length;
    [secondHalf[1], secondHalf[length - 2]] = [secondHalf[length - 2], secondHalf[1]];

    const encryptedPassword = firstHalf.concat(secondHalf);
    return encryptedPassword.join('');
}

function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypt(encryptedPassword);
}

function getRandomNumber(min = 0, max = 86) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getRandomPassword(length = 12) {
    const symbolArray = Array.from({ length: 87 }, (_, index) => String.fromCharCode(index + 33));
    const password = Array.from({ length }, () => symbolArray[getRandomNumber()]);
    return password.join('');
}
```
```js
/*
    logging and test function with console
*/

const password = getRandomPassword();
const encrypted = crypt(password);

console.log('Пароль:', password);
console.log('Зашифрованный пароль:', encrypted);
console.log('Проверка пароля:', checkPassword(encrypted, password));

const password2 = getRandomPassword();
const encrypted2 = crypt(password2).substring(1);

console.log('Пароль:', password2);
console.log('Зашифрованный пароль:', encrypted2);
console.log('Проверка пароля:', checkPassword(encrypted2, getRandomPassword()));
```

2024-11-05 19:01 UTC, merged